/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2019-10-04 07:29:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsps;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.ProductInfoModel;
import model.TagInfoModel;
import model.SlideInfoModel;
import model.TypeInfoModel;
import java.util.List;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.TagInfoModel");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.SlideInfoModel");
    _jspx_imports_classes.add("model.TypeInfoModel");
    _jspx_imports_classes.add("model.ProductInfoModel");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	List<SlideInfoModel> listSI = (List<SlideInfoModel>) request.getAttribute("listSI");
	List<TypeInfoModel> listTI = (List<TypeInfoModel>) request.getAttribute("listTI");
	List<TagInfoModel> listTag = (List<TagInfoModel>) request.getAttribute("listTag");
	List<ProductInfoModel> listPI = (List<ProductInfoModel>) request.getAttribute("listPI");
	ProductInfoModel pi = (ProductInfoModel) request.getAttribute("pi");
	int type = (Integer) request.getAttribute("type");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>CallGet</title>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/reset.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./top_menu.jsp", out, false);
      out.write("\n");
      out.write("<div class=\"section1\">\n");
      out.write("\t<div class=\"section1-container\">\n");
      out.write("\t\t<ul class=\"section1-slide-ul\" id=\"section1-slide-ul\">\n");
      out.write("\t\t\t");
for(int i=0; i<listSI.size(); i++){
				SlideInfoModel list = listSI.get(i);
				
      out.write("\n");
      out.write("\t\t\t\t<li class=\"section1-slide-li\">\n");
      out.write("\t\t\t\t\t<img src=\"upload/slide/");
      out.print(list.getIdx() );
      out.write('/');
      out.print(list.getImage() );
      out.write("\" />\n");
      out.write("\t\t\t\t\t");
if("".equals(list.getLink())==false && list.getLink() != null){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t<a class=\"section1-slide-link-btn\" href=\"");
      out.print(list.getLink());
      out.write("\" target=\"_blank\">");
      out.print(list.getLinkText() );
      out.write("</a>\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t</ul>\n");
      out.write("\t\t<a href=\"javascript: slideLeft();\" class=\"section1-slide-left-a\"><img src=\"images/left_arrow.png\" /></a>\n");
      out.write("\t\t<a href=\"javascript: slideRight();\" class=\"section1-slide-right-a\"><img src=\"images/right_arrow.png\" /></a>\n");
      out.write("\t\t<ul class=\"section-dot-ul\">\n");
      out.write("\t\t\t");
for(int i=0; i<listSI.size(); i++){
				SlideInfoModel list = listSI.get(i);
				if(i == 0){
				
      out.write("\n");
      out.write("\t\t\t\t\t<li class=\"section-dot-li dot-active\" id=\"section1-dot-");
      out.print(i+1);
      out.write("\" onclick=\"javascript: goSlideMove(");
      out.print(i+1);
      out.write(");\"></li>\n");
      out.write("\t\t\t\t");
}else{ 
      out.write("\n");
      out.write("\t\t\t\t\t<li class=\"section-dot-li\" id=\"section1-dot-");
      out.print(i+1);
      out.write("\" onclick=\"javascript: goSlideMove(");
      out.print(i+1);
      out.write(");\"></li>\n");
      out.write("\t\t\t\t");
}
			}
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t</ul>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<div class=\"section2\" >\n");
      out.write("\t<div class=\"type-container\">\n");
      out.write("\t\t<ul class=\"type-ul\">\n");
      out.write("\t\t\t<li class=\"type-li\" onclick=\"javascript: location.href='main.cg?type=0'\"><img class=\"type-img\" src=\"images/type-all.png\" /><span class=\"type-text\">전체보기</span></li>\n");
      out.write("\t\t\t");
for(int i=0; i<listTI.size(); i++){
				TypeInfoModel list = listTI.get(i);
				
      out.write("\n");
      out.write("\t\t\t\t<li class=\"type-li\" onclick=\"javascript: location.href='main.cg?type=");
      out.print(list.getIdx() );
      out.write("'\"><img class=\"type-img\" src=\"upload/type/");
      out.print(list.getIdx() );
      out.write('/');
      out.print(list.getImage() );
      out.write("\" /><span class=\"type-text\">");
      out.print(list.getTitle() );
      out.write("</span></li>\t\n");
      out.write("\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t</ul>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"tag-container\">\n");
      out.write("\t\t<ul class=\"tag-ul\">\n");
      out.write("\t\t\t");
for(int i=0; i<listTag.size(); i++){
				TagInfoModel list = listTag.get(i);
				
      out.write("\n");
      out.write("\t\t\t\t<li class=\"tag-li\"><a href=\"");
      out.print(list.getLink() );
      out.write("\" class=\"tag-a\" target=\"_blank\">#");
      out.print(list.getTitle() );
      out.write("</a></li>\n");
      out.write("\t\t\t");
} 
      out.write("\n");
      out.write("\t\t</ul>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<div class=\"product-container\" >\n");
      out.write("\t\t<img src=\"images/callforyou.png\" class=\"product-title\" />\n");
      out.write("\t\t<ul class=\"product-ul\" id=\"product_ul\">\n");
      out.write("\t\t\t");
for(int i=0; i<listPI.size(); i++){
				ProductInfoModel list = listPI.get(i);
				String piSplit[] = list.getTag().split(",");
				String tag = "";
				for(int j=0; j<piSplit.length; j++){
					if(j == 0)	tag = "#"+piSplit[j];
					else		tag+= " #"+piSplit[j];
				}
				
      out.write("\n");
      out.write("\t\t\t\t<li class=\"product-li\" onclick=\"javascript: location.href='product.cg?menu=product_detail&idx=");
      out.print(list.getIdx());
      out.write("'\">\n");
      out.write("\t\t\t\t\t<div class=\"product-back\" style=\"background-image: url('upload/product/");
      out.print(list.getIdx());
      out.write('/');
      out.print(list.getListThumb());
      out.write("')\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"product-cover\">\n");
      out.write("\t\t\t\t\t\t<div class=\"tack-div\"><span class=\"tack-count\">");
      out.print(list.getCount() );
      out.write("</span><img class=\"tack-call\" src=\"images/tack_call.png\" /></div>\n");
      out.write("\t\t\t\t\t\t<img class=\"product-one\" src=\"upload/product/");
      out.print(list.getIdx() );
      out.write('/');
      out.print(list.getOneThumb() );
      out.write("\" />\n");
      out.write("\t\t\t\t\t\t<div class=\"product-content-div\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"product-company1\">");
      out.print(list.getCompany1() );
      out.write("</span>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"product-x\">X</span>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"product-company2\">");
      out.print(list.getCompany2() );
      out.write("</span>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"product-name\">");
      out.print(list.getName() );
      out.write("</span>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"product-line\"></span>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"product-tag\">");
      out.print(tag );
      out.write("</span>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"product-description\">");
      out.print(list.getDescription().replaceAll("\n", "<br/>") );
      out.write("</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t");
} 
      out.write("\n");
      out.write("\t\t</ul>\n");
      out.write("\t\t<div style=\"width: 100%; clear: both; height: 0px;\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<a href=\"javascript: moreBtn();\" class=\"more-btn\"><img src=\"images/more.png\" /></a>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("</div>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("var slideListSize = ");
      out.print(listSI.size());
      out.write(";\n");
      out.write("var slideIdx = 1;\n");
      out.write("\n");
      out.write("$(document).ready(function() {\n");
      out.write("\tvar slideSize = 1480*slideListSize;\n");
      out.write("\t$(\"#section1-slide-ul\").css(\"width\", slideSize+\"px\");\n");
      out.write("\tsetInterval(\"autoSlideMove()\", 5000);\n");
      out.write("});\n");
      out.write("\n");
      out.write("function slideLeft(){\n");
      out.write("\t//alert($(\"#section1-slide-ul\").position().left);\n");
      out.write("\tif(slideIdx>1){\n");
      out.write("\t\tvar pLeft = $(\"#section1-slide-ul\").position().left;\n");
      out.write("\t\t$(\"#section1-slide-ul\").css(\"left\", (pLeft+1480)+\"px\");\n");
      out.write("\t\tslideIdx--;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfor(var i=1; i<=slideListSize; i++){\n");
      out.write("\t\tif(i == slideIdx)\n");
      out.write("\t\t\t$(\"#section1-dot-\"+i).addClass(\"dot-active\");\n");
      out.write("\t\telse\n");
      out.write("\t\t\t$(\"#section1-dot-\"+i).removeClass(\"dot-active\");\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("\n");
      out.write("function slideRight(){\n");
      out.write("\t//alert($(\"#section1-slide-ul\").position().left);\n");
      out.write("\tif(slideIdx<slideListSize){\n");
      out.write("\t\tvar pLeft = $(\"#section1-slide-ul\").position().left;\n");
      out.write("\t\t$(\"#section1-slide-ul\").css(\"left\", (pLeft-1480)+\"px\");\n");
      out.write("\t\tslideIdx++;\n");
      out.write("\t}\n");
      out.write("\telse{\n");
      out.write("\t\t$(\"#section1-slide-ul\").css(\"left\", \"0px\");\n");
      out.write("\t\tslideIdx = 1;\n");
      out.write("\t}\n");
      out.write("\tfor(var i=1; i<=slideListSize; i++){\n");
      out.write("\t\tif(i == slideIdx)\n");
      out.write("\t\t\t$(\"#section1-dot-\"+i).addClass(\"dot-active\");\n");
      out.write("\t\telse\n");
      out.write("\t\t\t$(\"#section1-dot-\"+i).removeClass(\"dot-active\");\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("\n");
      out.write("function goSlideMove(idx){\n");
      out.write("\tvar pLeft = (idx-1)*1480;\n");
      out.write("\t$(\"#section1-slide-ul\").css(\"left\", \"-\"+pLeft+\"px\");\n");
      out.write("\tslideIdx = idx;\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("\n");
      out.write("function autoSlideMove(){\n");
      out.write("\t\n");
      out.write("\tif(slideIdx<slideListSize){\n");
      out.write("\t\tvar pLeft = (slideIdx)*1480;\n");
      out.write("\t\t$(\"#section1-slide-ul\").css(\"left\", \"-\"+pLeft+\"px\");\n");
      out.write("\t\tslideIdx++;\n");
      out.write("\t}\n");
      out.write("\telse{\n");
      out.write("\t\t$(\"#section1-slide-ul\").css(\"left\", \"0px\");\n");
      out.write("\t\tslideIdx=1;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfor(var i=1; i<=slideListSize; i++){\n");
      out.write("\t\tif(i == slideIdx)\n");
      out.write("\t\t\t$(\"#section1-dot-\"+i).addClass(\"dot-active\");\n");
      out.write("\t\telse\n");
      out.write("\t\t\t$(\"#section1-dot-\"+i).removeClass(\"dot-active\");\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("\n");
      out.write("var pageNum = 1;\n");
      out.write("var type = ");
      out.print(type);
      out.write(";\n");
      out.write("var listCount = ");
      out.print(pi.getListCount() );
      out.write(";\n");
      out.write("\n");
      out.write("function moreBtn(){\n");
      out.write("\tpageNum++;\n");
      out.write("\t\n");
      out.write("\tvar param = \"mode=product_list&pageNum=\"+encodeURIComponent(pageNum)+\"&type=\"+encodeURIComponent(type)+\"&listCount=\"+encodeURIComponent(listCount);\n");
      out.write("\t\n");
      out.write("\t$.ajax({\n");
      out.write("\t\ttype: \"POST\",\n");
      out.write("\t\turl: \"main.cg\",\n");
      out.write("\t\tdata: param,\n");
      out.write("\t\tdataType: 'text',\n");
      out.write("\t\tsuccess: function(ret){\n");
      out.write("\t\t\tvar obj = JSON.parse(ret);\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tfor(var i=0; i<obj.length; i++){\n");
      out.write("\t\t\t\t$(\"#product_ul\").append(\n");
      out.write("\t\t\t\t\t\t\"<li class=\\\"product-li\\\" onclick=\\\"javascript: location.href='product.cg?menu=product_detail&idx=\"+obj[i].idx+\"'\\\">\" +\n");
      out.write("\t\t\t\t\t\t\t\"<div class=\\\"product-back\\\" style=\\\"background-image: url('upload/product/\"+obj[i].idx+\"/\"+obj[i].listThumb+\"')\\\"></div>\" +\n");
      out.write("\t\t\t\t\t\t\t\"<div class=\\\"product-cover\\\">\" +\n");
      out.write("\t\t\t\t\t\t\t\t\"<div class=\\\"tack-div\\\"><span class=\\\"tack-count\\\">\"+obj[i].count+\"</span><img class=\\\"tack-call\\\" src=\\\"images/tack_call.png\\\" /></div>\" +\n");
      out.write("\t\t\t\t\t\t\t\t\"<img class=\\\"product-one\\\" src=\\\"upload/product/\"+obj[i].idx+\"/\"+obj[i].oneThumb+\"\\\" />\" +\n");
      out.write("\t\t\t\t\t\t\t\t\"<div class=\\\"product-content-div\\\">\" +\n");
      out.write("\t\t\t\t\t\t\t\t\t\"<span class=\\\"product-company1\\\">\"+obj[i].company1+\"</span>\" +\n");
      out.write("\t\t\t\t\t\t\t\t\t\"<span class=\\\"product-x\\\">X</span>\" +\n");
      out.write("\t\t\t\t\t\t\t\t\t\"<span class=\\\"product-company2\\\">\"+obj[i].company2+\"</span>\" +\n");
      out.write("\t\t\t\t\t\t\t\t\t\"<span class=\\\"product-name\\\">\"+obj[i].name+\"</span>\" +\n");
      out.write("\t\t\t\t\t\t\t\t\t\"<span class=\\\"product-line\\\"></span>\" +\n");
      out.write("\t\t\t\t\t\t\t\t\t\"<span class=\\\"product-tag\\\">\"+obj[i].tag+\"</span>\" +\n");
      out.write("\t\t\t\t\t\t\t\t\t\"<span class=\\\"product-description\\\">\"+obj[i].description+\"</span>\" +\n");
      out.write("\t\t\t\t\t\t\t\t\"</div>\" +\n");
      out.write("\t\t\t\t\t\t\t\"</div>\" +\n");
      out.write("\t\t\t\t\t\t\"</li>\"\t\n");
      out.write("\t\t\t\t);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
